name: Front-End CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Webpack build
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npx stylelint "**/*.scss"

      - name: Run tests
        run: npm test